# Zephyr 4.4 (SDK v1.0.1)
# prj.conf: 5 diagnostic LEDs + USB CDC ACM, LOG, BLE
#
# What's included:
#   - GPIO and PRINTK enabled
#   - USB CDC ACM enabled
#   - Serial/UART enabled
#   - LOG enabled in DEFERRED mode
#   - BLE stack enabled
#   - BT debug logging (for development purposes)
#
# Issues resolved:
#   - overcome a deadlock between LOG and CDC ACM by replacing (LOG_MODE_IMMEDIATE) with (LOG_MODE_DEFERRED)
#        - Immediate mode deadlocks because LOG calls CDC ACM synchronously, which
#          blocks on USB enumeration.
#        - Deferred mode puts LOG messages in a ring buffer; a low-priority (lower than USB_Init()) LOG thread drains them later, after USB is up.

# === Kernel ===
CONFIG_MULTITHREADING=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_HEAP_MEM_POOL_SIZE=4096
CONFIG_MAIN_STACK_SIZE=2048
# 1 kHz tick for fine k_sleep granularity (default was 100Hz)
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000


# === Logging ===
CONFIG_LOG=y
# Fixes the LOG - CDC ACM deadlock at initialization
CONFIG_LOG_MODE_DEFERRED=y
# INFO (INF) logging
CONFIG_LOG_DEFAULT_LEVEL=3
# Absorb boot-time logs
CONFIG_LOG_BUFFER_SIZE=8192
# safeguard to make sure the USB enumerates first
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=2000
# route logs to CDC ACM
CONFIG_LOG_BACKEND_UART=y
CONFIG_PRINTK=y 

# === USB (CDC ACM console) ===
# Enable the new USB stack (Zephyr 4.x)
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y
# Console routing (printk goes to CDC ACM)
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
# USB logs at WRN level (we want to see USB problems, but not debug spam)
CONFIG_USBD_LOG_LEVEL_WRN=y

# === Hardware ===
CONFIG_GPIO=y
CONFIG_PINCTRL=y

# === BLE (Phase 2 baseline) ===
# We will enable all BLE roles now so we don't have to rebuild later:
#   - OBSERVER:   used for scanning (default state, listens to mobiles advertisments)
#   - CENTRAL:    used for auth (initiate connection to phone)
#   - PERIPHERAL: used for pairing mode (advertise, accept connection from phone)
#   - SMP:        security manager (used for pairing, encryption)
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_CENTRAL=y
CONFIG_BT_OBSERVER=y
# security manager (later)
CONFIG_BT_SMP=y
# for pairing service (later)
CONFIG_BT_GATT_DYNAMIC_DB=y
CONFIG_BT_MAX_CONN=2
CONFIG_BT_DEVICE_NAME="smart-lock-gate"
# verbose BLE logs during development (will be off in production)
#CONFIG_BT_LOG_LEVEL_DBG=y
CONFIG_BT_LOG_LEVEL_INF=y